def f(par2,par1):
    return par2 + par1

print(f(par2=1,2)) # exception 